### ISSUE TITLE
Number 1 is accepted for enum [1.0]

### ISSUE THREAD

**Issue by wromijn** [leadpony/justify#1]
I was using justify in a unit test to validate my API output format and noticed that a property of type "number" with value 1 validates against the enum [1.0]. I expected it not to validate, because 1 is not strictly equal to 1.0.

For me, the difference is important. When my API outputs 1, a client could think that the number is always integer. When it outputs 1.0 instead, they understand that it is a floating point value.

**Comment by leadpony** [comment]
Hello @wromijn 

Thank you so much for using this library.

In JSON world, 1.0 strictly equals to 1 because there is no distinction between integer and floating number.
JSON Schema specification explains instance equality 
at <http://json-schema.org/latest/json-schema-core.html#rfc.section.4.2.3>.

    both are numbers, and have the same mathematical value 

Alsp note that _integer_ in JSON Schema means a number without fractional part
or with only zeros in fractional part. 
Therefore 1.0 must be treated as a valid integer in JSON Schema.
Please see the test case at 
<https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/master/tests/draft7/optional/zeroTerminatedFloats.json>.

**Comment by wromijn** [comment]
You're right! The specification also says: "Whitespace and formatting concerns, including different lexical representations of numbers that are equal within the data model, are thus outside the scope of JSON Schema.". I will need to test this in another way then. Thank you for your quick answer!
