### ISSUE TITLE
Fails to handle mutual exclusion dependencies

### ISSUE THREAD

**Issue by kerrykimbrough** [leadpony/justify#11]
Found in 0.15.0 and 0.11.0. See attached schema and instance. 

The problem concerns the dependencies defined in definitions/condition/properties/between. The `between` schema should match an instance that has either a "min" property or an "exclusiveMin" property but not both. Similarly, an instance must have either 
a "max" property or an "exclusiveMax" property but not both. But validation of correct instances always fails.

[system-input-schema.json.txt](https://github.com/leadpony/justify/files/3027294/system-input-schema.json.txt)

[system-input-instance.json.txt](https://github.com/leadpony/justify/files/3027295/system-input-instance.json.txt)

**Comment by leadpony** [comment]
Hi @kerrykimbrough .
The `properties` keyword in the JSON schema means "if the object has the property X then validate its value against the subschema S. If the object does not have the property then ignore the subschema S and the object is just valid".
```json
{
  "properties": {
    "X": S
   }
}
```
The following snipet from your schema
```json
{
  "properties": {
    "exclusiveMin": {}
   }
}
``` 
is always evaluated as *valid*, regardless the existence of the property, because the empty schema `{ }` validates anything as valid.
And you negate the result using `not` keyword as below:
```json
"not": {
  "properties": {
    "exclusiveMin": {}
   }
}
```
Then the result is always *invalid*, regardless of the existence of the property `exclusiveMin` ! 
Each entry in the `dependencies` keyword in your schema has the same problem as explained here.
Could you please check your schema again?

**Comment by kerrykimbrough** [comment]
You're right, I misunderstood the semantics of property validation. Thanks for explaining!

I was able to successfully rework the dependencies as follows.

```
"minProperties": 3,
"maxProperties": 3,
"dependencies": {
    "min": {
        "properties": {
            "exclusiveMin": false
        }
    },
    "max": {
        "properties": {
            "exclusiveMax": false
        }
    }
}
```
