### ISSUE TITLE
Can't figure out this error: "JsonValidatingException At least one of the following sets of problems must be resolved."

### ISSUE THREAD

**Issue by rrodini** [leadpony/justify#21]
I have a Json schema file see attachment that justify doesn't like.  I have run this schema file through several online json schema validators that say it's okay, but not justify.  The error message does not help me fix the problem.  Please help.

[playerFile.schema.json.txt](https://github.com/leadpony/justify/files/3326962/playerFile.schema.json.txt)

**Comment by leadpony** [comment]
Hello @rrodini
Thank you for using this library.
I will inspect the error cause and reply to you.
A workaround is removing the last whitespace of the "$id" value at 16th line of your schema.
Sorry for inconvenience.

**Comment by rrodini** [comment]
Thanks so much.  I don't think I could have every caught that.
Looks like great software.
@rrodini
________________________________

**Comment by leadpony** [comment]
Hello @rrodini 
This library validates every schema by default against the official meta-schema provided by json-schema.org while it is being loaded. The meta-schema states the value of `$id` keyword must be a valid URI reference, and both URI and URI reference does not permit trailing spaces according to [RFC 3986](https://tools.ietf.org/html/rfc3986). 

Please note that `java.net.URI` class also throws an exception if it is given a string with trailing spaces,  although I am not using  the class for the validation purpose.

You may feel the error message is not so friendly for end users. I feel so too.
This is because the meta-schema is using `anyOf` keyword for the value of `items` keyword and my current implementation simply reports every possible solution to users. In future releases, it may hide and omit less possible solutions from the set of errors, based on some smart logic.
