### ISSUE TITLE
Validation error report is inconsistent and misleading

### ISSUE THREAD

**Issue by kerrykimbrough** [leadpony/justify#3]
First, let me say that Justify is an excellent system! It's exactly what I was hoping to find for use in my Tcases project.

I did encounter this issue with the way that validation errors are reported. It's a case in which 3 problem branches are listed. One branch reports the actual problem correctly, but the other two are either misleading or inconsistent with the facts of the situation. I regard this as a significant issue, because the usability of these error messages has a big impact on people using applications based on Justify.

See attached files. `system-input-schema.json` is the schema, and `system-input-values-missing.json` is the non-conforming instance. Justify reports the following problems.

```
Validating the JSON instance "system-input-values-missing.json"...
Exactly one of the following sets of problems must be resolved.
1) [line:44,column:13] The object must have a property whose name is "values".
2) Exactly one of the following sets of problems must be resolved.
   1) [line:12,column:36] The object must have at least 1 property(ies), but actual number is 0.
   2) [line:13,column:21] The object must have a property whose name is "members".
```

Problem 2.1 reports the actual violation of the assertion at line 68 of the schema. But problem 1 is misleading -- the specified object has a `members` property, so it could never match `#/definitions/var`; this has nothing to do with the real problem. Similarly, problem 2.2 is inconsistent -- the specified object already has a `values` property so it could never match `#/definitions/varSet`.

It seems that the implementation is failing to recognize an important distinction:  property doesn't exist vs. property value is invalid.

[system-input-schema.zip](https://github.com/leadpony/justify/files/2823174/system-input-schema.zip)

**Comment by leadpony** [comment]
Thank you for evaluating this library and sending such a detailed report.
I have reproduced the issue with your schema and instance materials.
Please give me time to look into the problem.

**Comment by leadpony** [comment]
I followed your instance and schema one by one.

- "Make" object to be tested against "#/definitions/function"
- "arg" object to be tested against "#/definitions/inputDef"
- "Color" object to be tested against "#/definitions/varDef"

The last "#/definitions/varDef" uses "oneOf" keyword,
therefore "Color" object must satisfy exactly one schema between:
(a) "#/definitions/var"
(b) "#/definitions/varSet"

Problem 1 comes from the schema (a) that insists that the object must have "values" property. 
But "Color" object does not have it.

The alternative solution is satisfying the schema (b).
"Color" object has "members" property so it's nice but all of its members 
must satisfy "#/definitions/varDef" again thorough "patternProperties" keyword.
Unfortunately the "Hue" property doesn't, because
- it has "values" property which has no properties (illegal by "#/definitions/var").
- it does not have "members" property (illegal by "#/definitions/varSet").

Please see the attached file in which I modified the instance 
according to the Problem 1 error message.
[system-input-values-fix-problem-1.json.txt](https://github.com/leadpony/justify/files/2824109/system-input-values-fix-problem-1.json.txt)

If I miss something, please do not hesitate to point out my error.

**Comment by kerrykimbrough** [comment]
I'm afraid you have misunderstood the issue. This is not a question -- I'm fully aware that this instance is non-conforming in a specific way. The problem is the way this error is reported.

The intention of the `oneOf` assertion is that `var` and `varSet` should be mutually exclusive -- exactly one of them must be satisfied. I realize now that the schema didn't do that correctly. Attached below is a revised schema that should fix that problem. Now the errors reported are different, but they still exhibit the same problems.

Here are the errors reported by the revised schema.
```
justify system-input-schema.json system-input-values-missing.json
Validating the JSON schema "system-input-schema.json"...
Done. 0 problem(s) were found.

Validating the JSON instance "system-input-values-missing.json"...
Exactly one of the following sets of problems must be resolved.
1) [line:10,column:25] The object must not have a property whose name is "members".
   [line:44,column:13] The object must have a property whose name is "values".
2) Exactly one of the following sets of problems must be resolved.
   1) [line:12,column:36] The object must have at least 1 property(ies), but actual number is 0.
   2) [line:12,column:32] The object must not have a property whose name is "values".
      [line:13,column:21] The object must have a property whose name is "members".
Done. 7 problem(s) were found.
```

Problem 1 is wrong: The `Color` value object **does** have a "members" property and it **does not** have a "values property. This message would be correct if it said "The members property does not have a valid value".

Similarly, Problem 2.2 is also wrong, for the same reason.

Problem 2.1 is the correct statement of the validation failure. This should be the only problem reported.

Notice that the corrected statements of 2.1 and 2.2 would **not** be alternatives to 2.1.  Instead, they are just additional context for the same (single) problem.

[system-input-schema.json.txt](https://github.com/leadpony/justify/files/2824802/system-input-schema.json.txt)

**Comment by leadpony** [comment]
Hello @kerrykimbrough, Thank you for sending a corrected schema.

"Color" object in the instance must satisfy exactly one of the following schema:
- "#/definitions/var"
- "#/definitions/varSet"

But actually the object satisfies neither of the schemas.

The message for the problem 1 tells how to fix the instance 
so that the object satisfies the first schema, that is  "#/definitions/var".
```
1) [line:10,column:25] The object must not have a property whose name is "members".
   [line:44,column:13] The object must have a property whose name is "values".
```
This message says:
- Remove the "members" property from the "Color" object.
- At the same time, add "values" property to the "Color" object.

According to the message, I modified the instance as below:
```
"Color": {
       "when": {
          "allOf": [ {"hasAll": ["small"]},  {"not": {"hasAny": ["polygon"]}}
            ]
            },
       "values": { "foo" : {} }
    },
```
Then I ran the validator again to find no problems in the instance. 
Therefore, the message for the problem 1 is **not** wrong 
and actually fix the instance.

Schema keywords such as "oneOf" and "anyOf" and possibly "not" introduce
the situation where there are multiple resolutions 
in order to correct the instance when the instance is not valid.

At the starting point of the development, I made a decision
that this library should provide the library users 
with all the possible resolutions found 
and does not automatically choose one
based on the specific algotirhm and/or criteria.

**Comment by leadpony** [comment]
I think what you really want to do can be achieved with the attached revised schema:
[system-input-schema-revised.json.txt](https://github.com/leadpony/justify/files/2825292/system-input-schema-revised.json.txt)
Please see the subschema at "#/definitions/varDef".  
```json
"varDef": {
    "type": "object",
    "properties": {
        "has": {
            "$ref": "#/definitions/annotation"
        },
        "when": {
            "$ref": "#/definitions/condition"
        },
        "values": {
            "type": "object",
            "minProperties": 1,
            "patternProperties": {
                ".": {
                    "$ref": "#/definitions/valueDef"
                }
            }
        },
        "members": {
            "type": "object",
            "minProperties": 1,
            "patternProperties": {
                ".": {
                    "$ref": "#/definitions/varDef"
                }
            }
        }
    },
    "additionalProperties": false,
    "oneOf": [
        {
            "required": [ "values" ],
            "properties": {
                "members": false
            }
        },
        {
            "required": [ "members" ],
            "properties": {
                "values": false
            }
        }
    ]
},
```

**Comment by kerrykimbrough** [comment]
Thanks, your suggested schema is a big improvement. Thanks also for you explanation of the behavior of the previous schema. You design decision makes sense to me now.
